import type { PropsTableGroup } from '@/components/common/props-table'
import type { GitSaturnRepo } from '@/components/custom/git-saturn'

export const demoGitSaturnData: {
  username: string
  repos: GitSaturnRepo[]
} = {
  username: 'satvik.dev',
  repos: [
    { name: 'design-system', commits: 312, stars: 940, lastActivity: '2 days ago' },
    { name: 'portfolio-site', commits: 198, stars: 620, lastActivity: '5 days ago' },
    { name: 'animation-kit', commits: 164, stars: 470, lastActivity: '1 week ago' },
    { name: 'ui-experiments', commits: 122 },
    { name: 'content-engine', commits: 86 },
    { name: 'shared-utils', commits: 64 },
    { name: 'api-gateway', commits: 241 },
    { name: 'auth-service', commits: 177 },
    { name: 'billing-engine', commits: 159 },
    { name: 'cache-layer', commits: 133 },
    { name: 'cli-toolkit', commits: 148 },
    { name: 'cms-core', commits: 214 },
    { name: 'color-system', commits: 121 },
    { name: 'component-lab', commits: 305 },
    { name: 'config-loader', commits: 117 },
    { name: 'content-pipeline', commits: 172 },
    { name: 'dashboard-app', commits: 229 },
    { name: 'data-viz-kit', commits: 168 },
    { name: 'db-migrations', commits: 111 },
    { name: 'design-tokens', commits: 189 },
    { name: 'devtools-panel', commits: 143 },
    { name: 'docs-site', commits: 257 },
    { name: 'email-worker', commits: 97 },
    { name: 'event-bus', commits: 124 },
    { name: 'feature-flags', commits: 118 },
    { name: 'forms-engine', commits: 176 },
    { name: 'git-hooks', commits: 88 },
    { name: 'graphql-api', commits: 246 },
    { name: 'grid-layouts', commits: 132 },
    { name: 'image-optimizer', commits: 165 },
    { name: 'insights-core', commits: 158 },
    { name: 'i18n-utils', commits: 109 },
    { name: 'job-queue', commits: 136 },
    { name: 'landing-builder', commits: 201 },
    { name: 'lint-config', commits: 92 },
    { name: 'logger-kit', commits: 101 },
    { name: 'markdown-renderer', commits: 127 },
    { name: 'media-proxy', commits: 116 },
    { name: 'metrics-agent', commits: 140 },
    { name: 'notification-hub', commits: 185 },
    { name: 'onboarding-flow', commits: 174 },
    { name: 'payment-ui', commits: 152 },
    { name: 'perf-monitor', commits: 126 },
    { name: 'plugin-sdk', commits: 208 },
    { name: 'preview-server', commits: 114 },
    { name: 'query-builder', commits: 166 },
    { name: 'rate-limiter', commits: 95 },
    { name: 'release-bot', commits: 87 },
    { name: 'search-indexer', commits: 144 },
    { name: 'session-store', commits: 119 },
    { name: 'state-machine', commits: 154 },
    { name: 'storage-adapter', commits: 113 },
    { name: 'style-guide', commits: 193 },
    { name: 'task-runner', commits: 139 },
    { name: 'theme-engine', commits: 181 },
    { name: 'ui-primitives', commits: 267 },
    { name: 'user-settings', commits: 142 },
    { name: 'video-processor', commits: 173 },
    { name: 'workflow-automator', commits: 221 },
    { name: 'webhook-relay', commits: 134 },
    { name: 'archive-service', commits: 96 },
    { name: 'backup-agent', commits: 108 },
    { name: 'badge-generator', commits: 77 },
    { name: 'build-cache', commits: 153 },
    { name: 'calendar-sync', commits: 128 },
    { name: 'chat-widget', commits: 207 },
    { name: 'checkout-flow', commits: 184 },
    { name: 'cloud-sync', commits: 146 },
    { name: 'code-snippets', commits: 83 },
    { name: 'compliance-tools', commits: 119 },
    { name: 'contact-center', commits: 162 },
    { name: 'cookie-manager', commits: 71 },
    { name: 'cron-orchestrator', commits: 138 },
    { name: 'customer-portal', commits: 215 },
    { name: 'data-collector', commits: 167 },
    { name: 'data-importer', commits: 149 },
    { name: 'dataset-cleaner', commits: 104 },
    { name: 'delivery-tracker', commits: 126 },
    { name: 'deployment-cli', commits: 112 },
    { name: 'docs-generator', commits: 131 },
    { name: 'edge-proxy', commits: 174 },
    { name: 'error-reporter', commits: 98 },
    { name: 'experiment-runner', commits: 158 },
    { name: 'file-browser', commits: 121 },
    { name: 'finance-dashboard', commits: 203 },
    { name: 'font-loader', commits: 69 },
    { name: 'geo-service', commits: 116 },
    { name: 'growth-tools', commits: 182 },
    { name: 'help-center', commits: 143 },
    { name: 'import-export', commits: 109 },
    { name: 'infra-scripts', commits: 194 },
    { name: 'integration-hub', commits: 171 },
    { name: 'invoice-core', commits: 124 },
    { name: 'knowledge-base', commits: 137 },
    { name: 'language-model-ui', commits: 226 },
    { name: 'layout-engine', commits: 147 },
    { name: 'lead-manager', commits: 118 },
    { name: 'link-shortener', commits: 93 },
    { name: 'live-updates', commits: 154 },
    { name: 'mail-templates', commits: 129 },
    { name: 'map-viewer', commits: 117 },
    { name: 'menu-builder', commits: 88 },
    { name: 'mobile-shell', commits: 176 },
    { name: 'monitoring-sdk', commits: 111 },
    { name: 'multi-tenant-core', commits: 199 },
    { name: 'oauth-bridge', commits: 107 },
    { name: 'ops-dashboard', commits: 166 },
    { name: 'package-registry', commits: 123 },
    { name: 'pdf-generator', commits: 145 },
    { name: 'policy-engine', commits: 132 },
    { name: 'pricing-service', commits: 157 },
    { name: 'product-catalog', commits: 213 },
    { name: 'project-board', commits: 169 },
    { name: 'prompt-library', commits: 101 },
    { name: 'qa-automation', commits: 188 },
    { name: 'realtime-sync', commits: 161 },
    { name: 'report-builder', commits: 179 },
    { name: 'request-tracker', commits: 114 },
    { name: 'resource-planner', commits: 141 },
  ],
}

export const gitSaturnPropGroups: PropsTableGroup[] = [
  {
    title: 'GitSaturn props',
    rows: [
      {
        prop: 'repos',
        type: `Array<{
  name: string;
  commits: number;
  stars?: number;
  lastActivity?: string;
}>`,
        required: true,
        description: 'List of repositories. Each repo becomes one orbiting meteoroid and its commits control the meteoroid size.',
      },
      {
        prop: 'username',
        type: 'string',
        required: false,
        description: 'Name shown in the badge under the planet.',
      },
      {
        prop: 'width',
        type: 'number',
        required: false,
        description: 'Sets the width of the rendered Saturn scene.',
      },
      {
        prop: 'height',
        type: 'number',
        required: false,
        description: 'Sets the height of the rendered Saturn scene.',
      },
      {
        prop: 'interactive',
        type: 'boolean',
        required: false,
        description: 'Enables orbit controls so the planet can be rotated and zoomed.',
      },
      {
        prop: 'className',
        type: 'string',
        required: false,
        description: 'Custom classes for the outer wrapper.',
      },
    ],
    children: [
      {
        title: 'repo item props',
        rows: [
          {
            prop: 'name',
            type: 'string',
            required: true,
            description: 'Repository name used as the stable key for each meteoroid.',
          },
          {
            prop: 'commits',
            type: 'number',
            required: true,
            description: 'Commit count for that repository. More commits create a larger meteoroid.',
          },
          {
            prop: 'stars',
            type: 'number',
            required: false,
            description: 'Optional star count shown in the focus card. If omitted, a readable fallback is derived.',
          },
          {
            prop: 'lastActivity',
            type: 'string',
            required: false,
            description: 'Optional last activity label shown in the focus card. If omitted, a relative fallback is derived.',
          },
        ],
      },
    ],
  },
]
